services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: quiz-frontend-prod
    container_name: quiz-frontend-prod-cont
    ports:
      - "4200:80"
    networks:
      - quiz-network
    restart: always
    cpu_period: 100000      # Default is 100,000 microseconds (100ms)
    cpu_quota: 5000        # 5% of the total CPU time
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: quiz-backend-prod
    container_name: quiz-backend-prod-cont
    ports:
      - "9090:9090"
    networks:
      - quiz-network
    restart: always
    cpu_period: 100000      # Default is 100,000 microseconds (100ms)
    cpu_quota: 5000        # 5% of the total CPU time

networks:
  quiz-network:  # Define the network