services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: quiz-frontend-prod
    container_name: quiz-frontend-prod-cont
    ports:
      - "4200:80"
    networks:
      - quiz-network
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    image: quiz-backend-prod
    container_name: quiz-backend-prod-cont
    ports:
      - "9090:9090"
    networks:
      - quiz-network
    restart: always

networks:
  quiz-network:  # Define the network