services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    image: quiz-frontend-prod
    container_name: quiz-frontend-prod-cont
    ports:
      - "4200:80"